### ISSUE TITLE
Can I disable Auth?

### ISSUE THREAD

**Issue by ms-jpq** [datarhei/restreamer#135]
Hi there,

Thank you for the really cool project, its lovely. :)
I was wondering if its possible to disable the built in auth? (I want to use a reverse proxy based solution instead)

I tried setting the env `RS_USERNAME` and `RS_PASSWORD` to empty string and it did not seem to work.

Thanks!

**Comment by ioppermann** [comment]
Hi @ms-jpq 

This is currently not implemented, no matter which value you choose for `RS_USERNAME` and `RS_PASSWORD`.

A way to explicitely switch off auth will be available in a future version.

**Comment by romanstech** [comment]
Hi,

Agree with this feature request. I prefer using an LDAP authentication on Nginx reverse proxy.

Thanks!

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by threehappypenguins** [comment]
> Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀 Have fun with it.

How do I disable auth? I have updated and I still can't find the feature. I see there is a checkmark beside `Login/JWT authorization` but I can't uncheck it (it's grayed out).

**Comment by threehappypenguins** [comment]
> > Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀 Have fun with it.
> 
> How do I disable auth? I have updated and I still can't find the feature. I see there is a checkmark beside `Login/JWT authorization` but I can't uncheck it (it's grayed out).

I figured it out. Since my config file for docker run is: `/opt/restreamer/config:/core/config` I navigated to `/opt/restreamer/config` and edited `config.json`. In it, I changed:

```
"auth": {
            "enable": true,
            "disable_localhost": false,
            "username": "myusername",
            "password": "mypassword",
            "jwt": {
                "secret": "mybiglongtoken"
            },
            "auth0": {
                "enable": false,
                "tenants": []
            }
```
to
```
"auth": {
            "enable": false,
            "disable_localhost": true,
            "username": "",
            "password": "",
            "jwt": {
                "secret": ""
            },
            "auth0": {
                "enable": false,
                "tenants": []
            }
```
Then I restarted the container. I want to use Authelia so I can enable 2FA.

**Comment by threehappypenguins** [comment]
Never mind. It doesn't work. I opened in incognito to test, and it wants me to set a username and password again. So how do I properly disable auth?

**Comment by threehappypenguins** [comment]
Aha. I finally figured it out. I have to add the environment variable `CORE_API_AUTH_ENABLE=false`

So for docker:

```
docker run -d --restart=always --name restreamer \
   -e CORE_API_AUTH_ENABLE=false \
   -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data \
   -p 8080:8080 -p 8181:8181 \
   -p 1935:1935 -p 1936:1936 \
   -p 6000:6000/udp \
   datarhei/restreamer:latest
```

I'm still not entirely sure how to make it so I can check and uncheck the `Login/JWT authorization` feature (it currently has a red `ENV` tag next to it which is expected with my set environment variable), but at least it works now.
