### ISSUE TITLE
Failed to verify the source. Please check the address.

### ISSUE THREAD

**Issue by prettydev** [datarhei/restreamer#547]
**Describe the bug**
https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8
It works normally with chrome hls player(https://chrome.google.com/webstore/detail/hls-player-m3u8-streaming/eakdijdofmnclopcffkkgmndadhbjgka?hl=en-US)
But can't import it as a network source on Restreamer.

**To Reproduce**
1. Go to 'Channels'
2. Click on '+'
3. Enter any channel name 'test' and click 'ADD' button
4. Select 'Network source'.
5. Type address 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8'
6. Type username and password and click 'NEXT' button
4. See error: 'Failed to verify the source. Please check the address.'

**Expected behavior**
Must be added as source stream.

**Screenshots**
![image](https://user-images.githubusercontent.com/53688893/234359197-e7e45fbb-6e6d-4cbd-86e1-b12cd601e945.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Browser [Chrome]
 - Version [Latest]

**Comment by jstabenow** [comment]
Done:
![Bildschirmfoto 2023-04-26 um 16 28 09](https://user-images.githubusercontent.com/7462030/234607871-bbf33fbf-f3d7-473b-b310-5b5853e5e548.png)

It seems the Restreamer could not connect to the stream/internet.
Please start the Docker container with `--security-opt seccomp=unconfined`.

**Comment by prettydev** [comment]
Still does not work for me. I'm using this command to run docker.
```
sudo docker run --security-opt seccomp=unconfined --detach --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest
```
I'm testing on ```http://localhost:8080/ui```
I'm still getting same errors.
I want to check detailed error logs but not sure where to find log files.
Hope you share some more detailed guide to test on local.
